### ISSUE TITLE
Seat 4 - error

### ISSUE THREAD

**Issue by MaximusLNK** [herpaderpaldent/seat-groups#132] opened 2020-10-16 10:26 UTC
Hello! I got an error while installing

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for herpaderpaldent/seat-groups ^1.7 -> satisfiable by herpaderpaldent/seat-groups[1.7.0, 1.7.1, 1.7.2].
>     - Can only install one of: eveseat/web[4.2.2, 3.0.x-dev].
>     - Can only install one of: eveseat/web[3.0.x-dev, 4.2.2].
>     - Can only install one of: eveseat/web[3.0.x-dev, 4.2.2].
>     - Conclusion: install eveseat/web 3.0.x-dev
>     - Installation request for eveseat/web (locked at 4.2.2, required as ^4.0) -> satisfiable by eveseat/web[4.2.2].

But my conditions are successfull...

SeAT Web 
Installed: v4.2.2
Current: 
Url: https://github.com/eveseat/web

This issue appeared after upgrading from version Seat 3 to Seat 4

**Comment by herpaderpaldent** [comment] 2020-10-16 10:29
Duplicate of https://github.com/herpaderpaldent/seat-groups/issues/131

**Closed as completed by herpaderpaldent** 2020-10-16 10:29 UTC
Labels: duplicate
