### ISSUE TITLE
Sequence of deletion can break seat-groups

### ISSUE THREAD

**Issue by Crypta-Eve** [herpaderpaldent/seat-groups#27] opened 2018-09-17 13:37 UTC
## What happened
I have an auto seat group (Corp1Members) which is given to all members of Corp1. It assigns the role Corp1Membership. I deleted the role Corp1Membership, however the seat-group remained (Corp1Members). When I went to edit the seat-group to remove it, SeAT errored every time.

## How I fixed it
```
delete from corporation_info_seatgroup;
delete from seatgroups;
```
the above removed all the groups and I was in the clear to work again.

## What I would have expected
I would have expected that when I removed the role (Corp1Membership) that either, the seatgroup (Corp1Members) would be left without a role, or that the seat-group would be removed as well.

**Comment by herpaderpaldent** [comment] 2018-09-18 05:48
i need to confirm this, i might have missed smth in the migration not to delete on cascade

**Comment by herpaderpaldent** [comment] 2018-09-20 12:09
Hey @Crypta-Eve 
I tried to reproduce this error but however i am not able to do so. As i was expecting the foreign key refrence deletes the row on delete: 

This is the DDL of the corresponding table:
```
create table role_seatgroup
(
  role_id      int unsigned not null,
  seatgroup_id int unsigned not null,
  primary key (role_id, seatgroup_id),
  constraint role_seatgroup_role_id_foreign
  foreign key (role_id) references roles (id)
    on delete cascade,
  constraint role_seatgroup_seatgroup_id_foreign
  foreign key (seatgroup_id) references seatgroups (id)
    on delete cascade
)
  collate = utf8mb4_unicode_ci;

create index role_seatgroup_role_id_index
  on role_seatgroup (role_id);

create index role_seatgroup_seatgroup_id_index
  on role_seatgroup (seatgroup_id);

```

I went further and manually deleted a role that was attached to a seat group. This resulted in the correct disassociation of the role with seat-group. The seat-group will keep existing but however you should be perfectly able to access it. 

Could you try to reproduce this error and append to this ticket the log entries caused by a potential error?

**Comment by Crypta-Eve** [comment] 2018-09-21 05:58
I will have another crack at it in a couple of days, away for the weekend sorry.

**Comment by herpaderpaldent** [comment] 2018-09-21 06:39
sure thing, i'll let it open until next week. If i am closing it before you are able to respond, just reopen it.

Have a great weekend

**Comment by herpaderpaldent** [comment] 2018-10-06 07:10
I am closing this issue due to inactivity.

**Closed by herpaderpaldent** 2018-10-06 07:10 UTC
Labels: possible bug, question
