### ISSUE TITLE
Problem with main char

### ISSUE THREAD

**Issue by marazmatik** [herpaderpaldent/seat-groups#15] opened 2018-07-30 09:03 UTC
If you have some characters, for example
Char1    - not in corp
char2    - in corp
char3  -  in corp
and make group, auto or manual, adding to group doesn't work.

**Comment by herpaderpaldent** [comment] 2018-07-30 10:18
Which Version of SeAT-Groups do you use? Which of these Chars is the Main?

**Comment by marazmatik** [comment] 2018-07-30 11:34
I have  a group of characters. Char milenium is in another corp then others
![image](https://user-images.githubusercontent.com/2928910/43394842-a7a6ab92-9404-11e8-9508-32fa3cb9bf76.png)

Create group and add this characters group in it
![image](https://user-images.githubusercontent.com/2928910/43394952-0f44c98c-9405-11e8-99ad-c9cb29b1bea0.png)

and if in this char_group main character isn't in corporation wich i give role in access managment, seat-group doen't addthis char_group to access role

**Comment by herpaderpaldent** [comment] 2018-07-30 12:39
First of all it is important to note that the affiliated corporation (available for whom) needs to be the same as your `main_character`. 
Furthermore: You have assigned managers. However managers are not entitled to be in a group. They still need to join the managed group. 

I hope this helps

**Comment by herpaderpaldent** [comment] 2018-07-30 14:07
I am closing this issue since OP misconceived managers to be member of the group. Instead by design a Manager must not be a member, he might but is not required to. 
A Manager is basically a Bouncer:
![image](https://user-images.githubusercontent.com/6583519/43402291-b4c3485e-9412-11e8-8a48-079826904440.png)

**Closed by herpaderpaldent** 2018-07-30 14:07 UTC

**Comment by aaronmallen** [comment] 2018-07-30 15:42
@herpaderpaldent I have actually seen a similar issue here.  If a user signs in with a character whose out of corp but then links a character in corp SeATGroups does not assign auto groups for the corp to the account group.  IMO this needs to be reopened and investigated.

**Comment by herpaderpaldent** [comment] 2018-07-30 17:38
> If a user signs in with a character whose out of corp but then links a character in corp SeATGroups does not assign auto groups for the corp to the account group

Works as designed. 

Reason: If  you purge a member from your corp, chance is high you miss an alt. You don't want that purged member to keep roles, just because you have forgotten to purge an alt.
