### ISSUE TITLE
seat-groups revoking superadmin of user "admin"

### ISSUE THREAD

**Issue by TyrHeimdal** [herpaderpaldent/seat-groups#21] opened 2018-09-10 14:53 UTC
Hi,

I have an issue after updating to the newest version, where it revokes my main admin account, which also has linked my main and all other alts.

This happens due to the missing token for the admin account, which I obviously cannot add.

I would just delete my main accounts and all alts and re-add them as alts of my main account to separate them, but due to other integrations (discord and discourse), I'd appreciate if I did not have to.

Has to be others who did the same thing as me when installing the SeAT application.

Is it possible that seat-groups can skip token checks for the hardcoded admin account?

Just to clarify;
The RefreshToken of admin is missing, therefore user group of *My Main* (admin, *My Main*, *redacted alts*) loses all permissions.

**Comment by dysath** [comment] 2018-09-10 17:20
I REALLY can not stress enough where you should not be using the 'admin' user, and just a main account with linked alts.

**Comment by TyrHeimdal** [comment] 2018-09-10 18:40
The point of the issue opened is that the admin accounts token should not matter. I can live with any other tokens screwing with my roles. That's easily fixable.

I would revert it to having it separate, but that would also mean a lot of issues with other connected services, mainly everything tied to my main discourse account. If you have a proper method of separating out the admin account from being linked to the rest, I'm all ears though.

Something tells me updating the group_id field in users and user_settings might not be enough, as it's tied up with other tables. The last thing I wanna do is manually update the DB and break the instance because I missed a table. I have no idea if SeAT recognizes group_id 1 as admin, or if it's based on the username.

**Comment by herpaderpaldent** [comment] 2018-09-10 20:03
Hey @TyrHeimdal 
Thank you for reporting this. Unfortunately it is not a bug but a configuration error you made by setting up your group. As @dysath explained you should never have the `admin` in your user group. 
This was unfortunately able prior `3.0.5` but we hindered users to keep doing so. 

I will not change the logic on SeAT Groups for a malconfiguration on yourside. Luckily there is a easy fix for this (or at least i hope so) : 
1. Somehow (either via cli create the admin link, or via db) receive superuser permission
2. navigate to: `/configuration/users`
3. delete `admin` user from your user-group

@warlof confirmed this might work. If not you might try:
```
INSERT INTO groups (created_at, updated_at) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
UPDATE users SET group_id = (SELECT MAX(id) FROM groups) WHERE group_id = (SELECT group_id FROM users WHERE name = 'admin') AND name <> 'admin';
``` (made by warlof, thank you for supporting <3)

I hope this helps you?

**Comment by TyrHeimdal** [comment] 2018-09-10 23:40
Hey @herpaderpaldent 
Bug or no bug, it was bugging me! Don't remember why it ended up that way, but everything was seemingly working fine - so I rolled with it (up until I ran into the issues after updating seat-groups).

Didn't want to bump the group_id without knowing how it would affect the existing information in other tables, and not knowing if admin was somehow hardcoded to gid 1 (makes sense to any Linux/UNIX, where "root" is just the name and you can't really screw with uid 0 as it's hardcoded in the kernel). My experience with Laravel is, unfortunately, very limited.

I took the approach of just rectifying the admin user by deleting it from my group and re-adding it with:
```
./artisan seat:admin:login
SeAT Admin Login URL Generator
User 'admin' does not exist. It will be created.
Searching for the 'Superuser' role
Checking if the Superuser role has the superuser permission
Adding the superuser permission to the role
Checking if 'admin' is a super user
Adding 'admin' to the Superuser role
Generating authentication token

Your authentication URL is valid for 60 seconds.
*REDACTED*
```
This worked out as intended.

Thanks for the assurances that deleting the admin user wouldn't screw up the instance. 👍 🥇

**Comment by herpaderpaldent** [comment] 2018-09-11 06:43
Perfect, glad we could work it out.

**Closed by herpaderpaldent** 2018-09-11 06:43 UTC
Labels: help wanted
